# Generated by Django 5.0.7 on 2024-07-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="propiedades",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios", to="web.propiedad"
            ),
        ),
    ]
