# Generated by Django 5.0.7 on 2024-07-24 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_alter_usuario_direccion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="RUT",
            new_name="rut",
        ),
    ]
